### ISSUE TITLE
Beta: panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by geeknik** [proabiral/inception#25]
While using the following provider with the beta branch commit 077172:
```
[
    {
        "vulnerability": "CRLF",
        "method": "GET",
        "color": "yellow",
        "body": "",
        "endpoint": [
            "/%%0a0aSet-Cookie:crlf=injection",
            "/%0aSet-Cookie:crlf=injection",
            "/%0d%0aSet-Cookie:crlf=injection",
            "/%0dSet-Cookie:crlf=injection",
            "/%23%0aSet-Cookie:crlf=injection",
            "/%23%0d%0aSet-Cookie:crlf=injection",
            "/%23%0dSet-Cookie:crlf=injection",
            "/%25%30%61Set-Cookie:crlf=injection",
            "/%25%30aSet-Cookie:crlf=injection",
            "/%250aSet-Cookie:crlf=injection",
            "/%25250aSet-Cookie:crlf=injection",
            "/%2e%2e%2f%0d%0aSet-Cookie:crlf=injection",
            "/%2f%2e%2e%0d%0aSet-Cookie:crlf=injection",
            "/%2F..%0d%0aSet-Cookie:crlf=injection",
            "/%3f%0d%0aSet-Cookie:crlf=injection",
            "/%3f%0dSet-Cookie:crlf=injection",
            "/%u000aSet-Cookie:crlf=injection"
        ],
        "headers": [],
        "checkIn": "responseHeader",
        "checkFor": "Set-Cookie:crlf=injection||||Set-Cookie: crlf=injection"
    }
]
```

I see the following crash:
```
Reading Providers from list at /root/test.json
Reading Domains from list at /tmp/domains.txt
Running test cases against provided domains .....
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x67e232]

goroutine 48 [running]:
main.stringReplacer(0xc000090240, 0x30, 0xc000090240, 0x30, 0x9, 0xc0000960e0)
        /root/go/src/github.com/proabiral/inception/main.go:101 +0x52
main.request(0xc0000945e0, 0x9, 0xc000094598, 0x4, 0xc00009459c, 0x3, 0x0, 0x0, 0xc0000ba280, 0x11, ...)
        /root/go/src/github.com/proabiral/inception/main.go:133 +0x17c
main.main.func1(0xc00009a3c0, 0xc00006c0c0, 0xc0000945f0)
        /root/go/src/github.com/proabiral/inception/main.go:334 +0x14e
created by main.main
        /root/go/src/github.com/proabiral/inception/main.go:326 +0x666

```

I'm using go version go1.13.4 linux/amd64.

**Comment by proabiral** [comment]
Thanks for raising the issue.

Endpoints `%%0a0aSet-Cookie:crlf=injection` and `%u000aSet-Cookie:crlf=injection` are not correctly URL encoded, which was causing the URL parser to crash.

The bug has been fixed by adding proper error handling when URL cannot be parsed.

**Comment by geeknik** [comment]
Thank you for fixing this issue, however, is there a way to silence the spam when a hostname doesn't resolve? For example:

```
[Get http://wb1.live.mapbox.com/foo#%27-(confirm)(%27openbugbounty%27)-%27: dial tcp: lookup wb1.live.mapbox.com: No address associated with hostname]
[Get http://stage.api.mapbox.com/foo#%27-(confirm)(%27openbugbounty%27)-%27: dial tcp: lookup stage.api.mapbox.com: No address associated with hostname]
[Get http://stage.api.mapbox.com/%0aSet-Cookie:crlf=injection: dial tcp: lookup stage.api.mapbox.com: No address associated with hostname]
[Get http://wb1.live.mapbox.com/%0aSet-Cookie:crlf=injection: dial tcp: lookup wb1.live.mapbox.com: No address associated with hostname]
[Get http://undefined.tiles.mapbox.com/foo#%27-(confirm)(%27openbugbounty%27)-%27: dial tcp: lookup undefined.tiles.mapbox.com: No address associated with hostname]
[Get http://undefined.tiles.mapbox.com/%0aSet-Cookie:crlf=injection: dial tcp: lookup undefined.tiles.mapbox.com: No address associated with hostname]
[Get http://testing.mapbox.com/foo#%27-(confirm)(%27openbugbounty%27)-%27: dial tcp: lookup testing.mapbox.com: No address associated with hostname]
[Get http://testing.mapbox.com/%0aSet-Cookie:crlf=injection: dial tcp: lookup testing.mapbox.com: No address associated with hostname]
[Get http://c.api.mapbox.com/%22%0D%0A/%3E%3Ch1%3E%3Ca%20href%3Dhttps://evil.com%3EYour%20password%20is%20currently%20unsafe,%20please%20click%20the%20link%20to%20update%20the%20information%3C/a%3E%3C/h1%3E/: dial tcp: lookup c.api.mapbox.com: No address associated with hostname]
[Get http://stage.api.mapbox.com/%22%0D%0A/%3E%3Ch1%3E%3Ca%20href%3Dhttps://evil.com%3EYour%20password%20is%20currently%20unsafe,%20please%20click%20the%20link%20to%20update%20the%20information%3C/a%3E%3C/h1%3E/: dial tcp: lookup stage.api.mapbox.com: No address associated with hostname]
```

Even using the `-silent` flag doesn't help silence this output.

**Comment by geeknik** [comment]
Thank you for fixing this issue, however, is there a way to silence the spam when a hostname doesn't resolve? For example:

```
[Get http://stage.api.mapbox.com/%0aSet-Cookie:crlf=injection: dial tcp: lookup stage.api.mapbox.com: No address associated with hostname]
[Get http://wb1.live.mapbox.com/%0aSet-Cookie:crlf=injection: dial tcp: lookup wb1.live.mapbox.com: No address associated with hostname]
[Get http://undefined.tiles.mapbox.com/%0aSet-Cookie:crlf=injection: dial tcp: lookup undefined.tiles.mapbox.com: No address associated with hostname]
[Get http://testing.mapbox.com/%0aSet-Cookie:crlf=injection: dial tcp: lookup testing.mapbox.com: No address associated with hostname]
```

Even using the `-silent` flag doesn't help silence this output.

**Comment by proabiral** [comment]
Thanks. This should be fixed now. Connection timeout / lookup error should now be visible only on verbose mode.
Let me know if there are any issues.
