### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by random-robbie** [proabiral/inception#8]
```
Reading Providers from list at /root/src/github.com/proabiral/inception/provider.json
Reading Domains from list at /root/src/github.com/proabiral/inception/domains.txt
Running test cases against provided domains ..... 
Issue detected : Web/Meta XML http://twitter.com/WEB-INF/web.xml response contains application/xml
panic: runtime error: index out of range

goroutine 5 [running]:
main.request(0xc000018b50, 0xb, 0xc0000185a0, 0x9, 0xc0000185aa, 0x6, 0xc000052380, 0x3, 0x4, 0xc0000185c0, ...)
        /root/src/github.com/proabiral/inception/main.go:131 +0xb18
main.main.func1(0xc0000544e0, 0xc00005e300, 0xc000018b90)
        /root/src/github.com/proabiral/inception/main.go:275 +0x14e
created by main.main
        /root/src/github.com/proabiral/inception/main.go:267 +0x53a
```

only thing changed is the provider.json but i always keep getting this? any ideas it's valid json?

**Comment by random-robbie** [comment]
Close it was due to a blind XSS payload i was trying.
